### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by tomhoward87** [virtan/eep#6]
In the "Also" section you describe the function for filtering calls to a specific module:

>Collect specific module calls only
>1> eep:start_file_tracing("file_name", [], my_module).

It looks like it should actually be to a list of modules:

>Collect specific module calls only
>1> eep:start_file_tracing("file_name", [], [my_module_1, my_module_2]).

**Comment by virtan** [comment]
Thanks for pointing.
Fixed.
